language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO="Django==1.10.2"
  - DJANGO="Django==2.0"
  - DJANGO="Django==1.11.8"

matrix:
  exclude:
    - env: DJANGO="Django==1.10.2"
      python: 3.3
    - env: DJANGO="Django==1.10.2"
      python: 2.7
    - env: DJANGO="Django==2.0"
      python: 2.7

install:
  - pip install $DJANGO
  - pip install factory-boy
  - pip install pytz
  - pip install coveralls
  - python setup.py develop

script:
  - cd example_project; coverage run manage.py test photologue

after_success:
  - coveralls

