# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0010_auto_20160105_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='subdomain',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='subdomain'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(help_text='A "slug" is a unique URL-friendly title for an object.', max_length=250, verbose_name='title slug'),
        ),
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=set([('slug', 'subdomain')]),
        ),
    ]
